In [4]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.vector_ar.var_model import VAR

import warnings
warnings.simplefilter('ignore')

In [5]:
PATH = 'dataset/test2.csv'
hai_data = pd.read_csv(PATH, parse_dates=['time'])

In [6]:
print(hai_data.shape)
hai_data.head()

(118801, 81)

,time,P1_B2004,P1_B2016,P1_B3004,P1_B3005,P1_B4002,P1_B4005,P1_B400B,P1_B4022,P1_FCV01D,...,P4_HT_PS,P4_LD,P4_ST_FD,P4_ST_GOV,P4_ST_LD,P4_ST_PO,P4_ST_PS,P4_ST_PT01,P4_ST_TT01,attack
0,2020-07-09 15:00:00,0.09874,1.25036,382.21698,1118.61084,32.0,99.98731,2835.65454,35.37903,92.69160,...,0,284.39673,-0.00231,15844.0,283.92651,293.51129,0,10051.0,27600.0,0
1,2020-07-09 15:00:01,0.09874,1.24944,382.21698,1118.61084,32.0,100.00000,2832.98731,35.37674,92.64934,...,0,283.47436,-0.00181,15808.0,283.36591,292.67938,0,10052.0,27600.0,0
2,2020-07-09 15:00:02,0.09874,1.24746,382.21698,1118.61084,32.0,99.98115,2842.25244,35.37178,92.91075,...,0,282.69678,0.00007,15734.0,282.93189,291.90179,0,10052.0,27595.0,0
3,2020-07-09 15:00:03,0.09874,1.24624,382.21698,1118.61084,32.0,100.00000,2833.12744,35.36873,92.92407,...,0,283.04034,0.00000,15710.0,282.06378,291.59430,0,10053.0,27590.0,0
4,2020-07-09 15:00:04,0.09874,1.24364,382.21698,1118.61084,32.0,100.00000,2839.44482,35.36224,93.05405,...,0,281.99145,-0.00029,15608.0,283.67334,289.87628,0,10052.0,27588.0,0

In [7]:
### DAILY AGGREGATION ###

df_day = pd.DataFrame()